### ISSUE TITLE
課題のページを表示したまま課題を削除すると戻れなくなる

### ISSUE THREAD

**Issue by Ryouma-Kawashima** [i-yuuki/tani-releases#1]
【再現手順】
1. ２画面モードになるまで画面を広くする
2. 課題を追加する
3. 課題ページを開く
4. クレジットなど他ページを開く
5. もう一度課題ページを開いて状態で消す
6. クレジットから戻るボタンを押す
7. ２画面の右側のページが空の状態になっていたら再現完了

**Comment by i-yuuki** [comment]
v0.0.2で修正 🍜
